site_name: BasicAngularApp
site_description: Documentation for BasicAngularApp
site_author: Ong Zhi Xian
site_url: https://ongzhixian.github.io/BasicAngularApp/
copyright: Copyright &copy; 2022 <a href="#">Ong Zhi Xian</a>
docs_dir: src
site_dir: ../docs/docs
nav:
  - Docs Home: index.md
  - User Guide:
    - Overview: user-guide/index.md
    - Page1: user-guide/sample-page1.md
    - Page2: user-guide/sample-page2.md
    - Configuration:
      - Page1: user-guide/configuration/config-page1.md
      - Page2: user-guide/configuration/config-page2.md
  - Developer Guide:
    - Overview: developer-guide/index.md
  - About:
    - Release Notes: about/release-notes.md
    - License: about/license.md